name: Publish Libraries

on:
  push:
    tags:
      - 'l*.*.*'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Use Node.js 22
        uses: actions/setup-node@v6
        with:
          node-version: 22
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test

      - name: Publish libraries
        run: npm publish --workspaces --if-present
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
